name: CI Pipeline
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - run: echo "- Build the artefact"
      - run: echo "- Upload the artefact"
      # - name: Upload the artefact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: artefact-name
      #     path: ./artefact-name

  deploy:
    environment: Development
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Auto-deploy the artefact to the development environment" 
  test-artifact:
    environment: Development
    needs: [build, deploy]
    runs-on: ubuntu-latest
    services:
      mock-for-application-under-test:
        image: hello-world
      app-under-test:
        image: hello-world

    steps:    
      # - uses: actions/checkout@v3
      - run: echo "- Simulate and test the artefact"      
      - run: echo "# Everything completed successfully!" >> $GITHUB_STEP_SUMMARY
