name: CI Pipeline
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - run: echo "- Setup environment, install Java, Maven ... "      
      - run: echo "- Build the artefact  with the respective command"
      - run: echo "- Upload the artefact"
      # - name: Upload the artefact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: artefact-name
      #     path: ./artefact-name

  deploy:
    environment: Development
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # - name: Download the artefact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: artefact-name
      - run: echo "- Setup environment for the deployment if needed ... "   
      - run: echo "- Auto-deploy the artefact to the development environment" 
      
  test-artifact:
    environment: Development
    needs: [build, deploy]
    runs-on: ubuntu-latest
    services:
      mock-for-application-under-test:
        image: hello-world
      app-under-test:
        image: hello-world

    steps:    
      # - uses: actions/checkout@v3
      - run: echo "- Setup environment for test run, install Java, Maven ... "      
      - name: Run tests
        id: test_run
        run: echo "- Simulate and test the artefact"        
        
      # - name: Upload test-report
      #   uses: actions/upload-artifact@v4
      #   if: always() 
      #   with:
      #     name: test-report
      #     path: |
      #       target/cucumber-html-reports
      #       target/report
      #     retention-days: 1
      
      - name: Publish successful summary
        if: always()  && steps.test_run.outcome == 'success'
        run: echo "# Everything completed successfully!" >> $GITHUB_STEP_SUMMARY

      - name: Publish failure summary
        if: always()  && steps.test_run.outcome == 'failure'
        run: echo "# Something went wrong!" >> $GITHUB_STEP_SUMMARY
