name: Example of Deployment Pipeline
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - run: echo "- Lint the code and run unit tests"

  build:
    needs: [integration]
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - run: echo "- Build the artefact"

  test-artifact:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - run: echo "- Simulate and test the artefact"

  development:
    environment: Development
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Auto-deploy the artefact to the development environment"

  staging:
    environment: Staging
    needs: [development, test-artifact]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "After development environment is deployed..."
          echo "and after the artefact tests have passed..."
          echo "- Auto-deploy the artefact to the staging environment"

  test-staging:
    needs: staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Test the staging environment"

  production:
    environment: Production
    needs: [test-staging]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "After staging environment is deployed..."
          echo "and after the staging tests have passed..."
          echo "require a review before deploying to the production environment, then..."
          echo "- Deploy the artefact to the production environment"

  test-production:
    needs: [production]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Test the artefact in the production environment"
      - run: echo "# Everything completed successfully!" >> $GITHUB_STEP_SUMMARY
